config/routes.rb
Rails.application.routes.draw do
  resources :sightings
  resources :animals
end

app/models/animal.rb
class Animal < ApplicationRecord
    has_many :sightings
    validates :name, :latin_name, :kingdom, presence: true
    validates :name, :latin_name, :kingdom, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
    belongs_to :animal
    validates :date, :time, :latitude, :longitude, :region, presence: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    
    def index
        @animals=Animal.all
    end
    
    def new
        @animals= Animal.new
    end
    
    def create
        @animals = Animal.new(animal_params)
        if @animals.save
            redirect_to animals_path
        else
            render action: :new
        end
    end
    
    def edit
        @animal=Animal.find(params[:id])
    end
    
    def update
        @animal =Animal.find(params[:id])
        if @animal.update_attributes(animal_params)
            redirect_to animals_path(@animal)
        else
            render action: :edit
        end
    end
    
    def destroy
        @animal=Animal.destroy(params[:id])
        if @animal.destroy
            redirect_to animals_path
        else
            render :destroy
        end 
    end
    
    def show 
        @animal=Animal.find(params[:id])
    end 
    
    
    private
    
    def animal_params
        params.require(:animal).permit(:name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
    
    def index
        @sighting=Sighting.all
    end

    def new
        animal = Animal.find(params[:animal_id])
        @sighting=animal.sightings.new
    end

    def create
        @sighting=Sighting.new(sightings_params)
        if @sighting.save
            redirect_to animal_path(@sighting.animal)
        else
            render action: :new
        end 
    end

    def edit
        @sighting=Sighting.find(params[:id])
    end

    def update
        @sighting=Sighting.find(params[:id])
        if @sighting.update_attributes(sightings_params)
            redirect_to animal_path(@sighting.animal)
        else 
            render action: :new
        end 
    end 

    def destroy
        @sighting=Sighting.destroy(params[:id])
        if @sighting.destroy
            redirect_to animal_path(@sighting.animal)
        else
            render action: :destroy
        end 
    end 
    
    private
    def sightings_params
        params.require(:sighting).permit(:animal_id, :date, :time, :latitude, :longitude, :region)
    end 

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/edit.html.erb
<h1>Edit the Animal</h1>

<%= form_for @animal do |f| %>

<%= f.label :name %>
<%= f.text_field :name%>

<%= f.label :latin_name %>
<%= f.text_field :latin_name%>

<%= f.label :kingdom %>
<%= f.text_field :kingdom%>



<%=f.submit%>
<%end%>

app/views/animals/index.html.erb
<h1>Welcome to Animal Wildlife Tracker!</h1>

<%= link_to 'Add an Animal', new_animal_path %>

<ul>
    <% @animals.each do |animal| %>
<%= animal.name %>
<button class="button is-link is-rounded"><%= link_to 'More info', animal_path(animal)%></button>
<%= link_to 'Update', edit_animal_path(animal)%>
<button type="button" class="btn btn-primary btn-lg"><%=button_to "Delete", animal, :method => :delete, data: {confirm: "Are you sure you want to delete?"} %></button>
<hr>
<%end%>
    
</ul>

app/views/animals/new.html.erb
<h1>Add the animal you spotted!</h1>

<%= form_for @animals do |e| %>

<%= e.label :name %>
<%= e.text_field :name%>

<%= e.label :latin_name %>
<%= e.text_field :latin_name%>

<%= e.label :kingdom %>
<%= e.text_field :kingdom%>



<%=e.submit%>
<%end%>

<%=link_to "Go Back Home", animals_path%>

app/views/animals/show.html.erb
<h1>Here is all the information we have on this animal</h1>

<%=@animal.name%>
<%=@animal.latin_name%>
<%=@animal.kingdom%>

<ul>
<%@animal.sightings.each do |sighting| %>
<li>Date:<%=sighting.date%> Time:<%=sighting.time%> Latitude:<%=sighting.latitude%> Longitude:<%=sighting.longitude%> Region:<%=sighting.region%><button type="button" class="btn btn-dark">
<%= link_to 'Update', edit_sighting_path(sighting)%></button><%=button_to "Delete", sighting, :method => :delete, data: {confirm: "Are you sure you want to delete?"} %></button>



</li>

<%end%>
</ul>

<%=link_to "Enter a new sighting", new_sighting_path({animal_id:@animal.id})%><br>
<%=link_to "Go Back to Home", animals_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/edit.html.erb
<h1>Whoops, saw the wrong siting!</h1>

<%= form_for @sighting do |f| %>
  <%= f.hidden_field :animal_id %>
    <%= f.label :date %>
  <%= f.text_field :date %></br>
    <%= f.label :time %>
  <%= f.text_field :time %></br>
    <%= f.label :latitude %>
  <%= f.text_field :latitude %></br>
    <%= f.label :longitude %>
  <%= f.text_field :longitude %></br>
    <%= f.label :region %>
  <%= f.text_field :region %></br>

  <%= f.submit "Create Sighting" %>
<% end %>

app/views/sightings/new.html.erb
<h1>Enter A New Sighting!</h1>

<%= form_for @sighting do |f| %>
  <%= f.hidden_field :animal_id %>
    <%= f.label :date %>
  <%= f.text_field :date %></br>
    <%= f.label :time %>
  <%= f.text_field :time %></br>
    <%= f.label :latitude %>
  <%= f.text_field :latitude %></br>
    <%= f.label :longitude %>
  <%= f.text_field :longitude %></br>
    <%= f.label :region %>
  <%= f.text_field :region %></br>

  <%= f.submit "Create Sighting" %>
<% end %>